apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
  - image: docker_container/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: docker_container/ticketing-client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: '**/*.js'
        dest: .
  - image: docker_container/tickets
    context: tickets
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: docker_container/orders
    context: orders
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: docker_container/expiration
    context: expiration
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: . 
  - image: docker_container/payments
    context: payments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: . 
